meta_name: "L'Atelier"
meta_title: "L'Atelier - Find the perfect supplier for you"
meta_description: "L'Atelier is a platform that connects clothing brands with suppliers. We want to allow young creator to find the perfect supplier for them in a matter of minutes"
meta_image: "cover.png"
